package com.doctor.spring4.common.mapper;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.doctor.spring4.config.DataSourceConfig.DbH2;

/**
 * 请用plsql developer special copy -> java　复制sql语句
 * 
 * @author doctor
 *
 * @time 2015年3月10日
 */

@DbH2
public interface UserMapper {

	@Update("create table if not exists \"${tableName}\" (" +
			"\"id\" bigint generated by default as identity," +
			"\"loginName\" varchar(255) not null unique," +
			"\"name\" varchar(64)," +
			"\"password\" varchar(255)," +
			"\"salt\" varchar(64)," +
			"\"email\" varchar(128)," +
			"\"status\" varchar(32)," +
			"\"teamId\" bigint," +
			"primary key (\"id\")" +
			")")
	void createUserTable(@Param("tableName") String tableName);

	@Select("select count(1)  from information_schema.tables t where t.table_name = #{tableName}")
	int existTable(String tableName);
}
