package com.doctor.mybatis3practice.mapper;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.doctor.mybatis3practice.domain.Product;

public interface ProductMapper {

	@Update("create table ${tableName} (productId int not null generated by default as identity (start with 1, increment by 1),  name varchar(80),	 description varchar(255),createTime timestamp , primary key (productId))")
	void createTable(@Param("tableName") String tableName);

	@Select("select count(1)  from sys.systables where LCASE(tablename)=#{tableName}")
	int existTable(@Param("tableName") String tableName);

	@Update("drop table   ${tableName} ")
	void dropTable(@Param("tableName") String tableName);

	@Insert("insert into ${tableName} ( name,description,createTime) values (#{product.name},#{product.description},#{product.createTime})")
	@Options(useGeneratedKeys = true, keyProperty = "product.productId")
	int insertProduct(@Param("tableName") String tableName, @Param("product") Product product);
}
